"call pathogen#runtime_append_all_bundles()
call pathogen#infect()
call pathogen#helptags()

set background=dark
let g:solarized_termtrans=1
let g:solarized_termcolors=256
let g:solarized_contrast="high"
let g:solarized_visibility="high"
colorscheme solarized

